# Generated by Django 3.2.6 on 2021-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Date_of_birth',
            field=models.DateField(default=2021),
        ),
    ]
